from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[4]
TN_STATE_CODE = "33"
TARGET_RECORDS = 12_000

REFERENCE_COLUMNS = [
    "reference_person_id", "reference_household_id", "source_record_id", "primary_source_id",
    "state", "state_code", "district", "district_code", "urban_rural",
    "age", "age_group", "gender", "marital_status", "relationship_to_head",
    "household_size", "household_type", "literacy_status", "education_level",
    "labour_force_status", "employment_status", "employment_type",
    "occupation_group", "industry_group", "individual_income", "household_income",
    "consumption_expenditure", "income_band", "dwelling_type", "house_ownership",
    "electricity", "drinking_water", "toilet_facility", "cooking_fuel",
    "health_insurance", "social_group", "survey_weight", "normalized_reference_weight",
    "calibrated_reference_weight_gender_ur", "reference_year", "record_quality_flag",
]

DATA_DIRS = [
    "data/raw/census", "data/raw/plfs", "data/raw/tn_des", "data/raw/data_gov_in",
    "data/processed", "data/reference", "data/calibration", "data/exports",
    "data/reports", "data/metadata", "reports",
]

SOURCE_ROWS = [
    {
        "source_id": "SRC_PLFS_2024_OPENCITY_PUBLIC_MIRROR",
        "source_name": "Periodic Labour Force Survey 2024 public-use individual and household data mirror",
        "publisher": "OpenCity mirror of MoSPI / NSO public-use PLFS data",
        "official_or_secondary": "Trusted secondary mirror of official microdata",
        "source_url": "https://data.opencity.in/dataset/periodic-labour-force-survey-plfs-2024",
        "download_url": "https://data.opencity.in/dataset/54aee23e-750b-4ba8-a8b9-9dc3651ffee7/resource/dfc2b79b-de80-4f0d-8188-aaaa0cf00fb6/download/799f375e-1cfd-4a11-9b85-1b746234b950.zip",
        "dataset_name": "PLFS 2024 personal and household data",
        "dataset_description": "Public-use PLFS person and household records filtered to Tamil Nadu.",
        "reference_year": "2024", "publication_year": "2025 mirror metadata",
        "geographic_level": "State, district, rural/urban", "unit_of_observation": "Person and household survey records",
        "file_format": "CSV/ZIP", "license_or_usage_notes": "Respect MoSPI source terms; OpenCity provides a public mirror.",
        "download_date": "", "access_status": "DOWNLOADED",
        "variables_of_interest": "age, gender, district, rural/urban, education, employment, occupation, industry, earnings, household size, social group, consumption, weights",
        "quality_notes": "Direct row-level source for the reference template.",
    },
    {
        "source_id": "SRC_TN_DES_GLANCE_2023_24", "source_name": "Tamil Nadu At a Glance 2023-2024",
        "publisher": "Department of Economics and Statistics, Government of Tamil Nadu",
        "official_or_secondary": "Official", "source_url": "https://des.tn.gov.in/index.php/en/node/346",
        "download_url": "https://des.tn.gov.in/sites/default/files/2025-03/Tamilnadu%20at%20a%20glance%202023-2024%20for%20des%20website%20(1)_0.pdf",
        "dataset_name": "Tamil Nadu At a Glance 2023-2024",
        "dataset_description": "Official state-level demographic and socioeconomic publication.",
        "reference_year": "2011; 2023-24", "publication_year": "2025",
        "geographic_level": "State", "unit_of_observation": "Aggregate statistic",
        "file_format": "PDF", "license_or_usage_notes": "Official DES publication.",
        "download_date": "", "access_status": "DOWNLOADED",
        "variables_of_interest": "population, literacy, workers, SC/ST, vital statistics, economy",
        "quality_notes": "Used for aggregate calibration/validation targets.",
    },
    {
        "source_id": "SRC_CENSUS_PCA_SD_2011", "source_name": "Primary Census Abstract, state/district level, 2011",
        "publisher": "Office of the Registrar General & Census Commissioner, India",
        "official_or_secondary": "Official", "source_url": "https://censusindia.gov.in/nada/index.php/catalog/6191",
        "download_url": "https://censusindia.gov.in/nada/index.php/catalog/6191",
        "dataset_name": "PC11_PCA-SD", "dataset_description": "Official Census 2011 PCA indicators.",
        "reference_year": "2011", "publication_year": "2021 catalog metadata",
        "geographic_level": "State, district", "unit_of_observation": "Aggregate geography",
        "file_format": "HTML/XLSX catalog", "license_or_usage_notes": "Official public Census table; cite ORGI.",
        "download_date": "", "access_status": "DOWNLOADED",
        "variables_of_interest": "population, male/female population, rural/urban population, literacy, workers",
        "quality_notes": "Census website downloads can timeout; DES publication carries key Census 2011 values.",
    },
    {
        "source_id": "SRC_TN_DES_EDUCATION_2022_23", "source_name": "Tamil Nadu Statistical Handbook 2022-23: Education",
        "publisher": "Department of Economics and Statistics, Government of Tamil Nadu", "official_or_secondary": "Official",
        "source_url": "https://des.tn.gov.in/index.php/en/node/346", "download_url": "",
        "dataset_name": "Education", "dataset_description": "Education handbook chapter.",
        "reference_year": "2022-23", "publication_year": "2025", "geographic_level": "State, district",
        "unit_of_observation": "Aggregate statistic", "file_format": "PDF", "license_or_usage_notes": "Official DES publication.",
        "download_date": "", "access_status": "DOWNLOADED", "variables_of_interest": "education indicators",
        "quality_notes": "Raw PDF stored; detailed table extraction pending.",
    },
    {
        "source_id": "SRC_TN_DES_AREA_POP_2022_23", "source_name": "Tamil Nadu Statistical Handbook 2022-23: Area and Population",
        "publisher": "Department of Economics and Statistics, Government of Tamil Nadu", "official_or_secondary": "Official",
        "source_url": "https://des.tn.gov.in/index.php/en/node/346", "download_url": "",
        "dataset_name": "Area and Population", "dataset_description": "Area/population handbook chapter.",
        "reference_year": "2011; 2022-23", "publication_year": "2025", "geographic_level": "State, district",
        "unit_of_observation": "Aggregate statistic", "file_format": "PDF", "license_or_usage_notes": "Official DES publication.",
        "download_date": "", "access_status": "DOWNLOADED", "variables_of_interest": "population, area, density",
        "quality_notes": "Raw PDF stored; detailed extraction pending.",
    },
    {
        "source_id": "SRC_TN_DES_EMPLOYMENT_2022_23", "source_name": "Tamil Nadu Statistical Handbook 2022-23: Employment",
        "publisher": "Department of Economics and Statistics, Government of Tamil Nadu", "official_or_secondary": "Official",
        "source_url": "https://des.tn.gov.in/index.php/en/node/346", "download_url": "",
        "dataset_name": "Employment", "dataset_description": "Employment handbook chapter.",
        "reference_year": "2022-23", "publication_year": "2025", "geographic_level": "State, district",
        "unit_of_observation": "Aggregate statistic", "file_format": "PDF", "license_or_usage_notes": "Official DES publication.",
        "download_date": "", "access_status": "DOWNLOADED", "variables_of_interest": "employment indicators",
        "quality_notes": "Raw PDF stored; PLFS remains row-level source.",
    },
    {
        "source_id": "SRC_TN_DES_HOUSING_2022_23", "source_name": "Tamil Nadu Statistical Handbook 2022-23: Housing and Building Activity",
        "publisher": "Department of Economics and Statistics, Government of Tamil Nadu", "official_or_secondary": "Official",
        "source_url": "https://des.tn.gov.in/index.php/en/node/346", "download_url": "",
        "dataset_name": "Housing and Building Activity", "dataset_description": "Housing handbook chapter.",
        "reference_year": "2022-23", "publication_year": "2025", "geographic_level": "State, district",
        "unit_of_observation": "Aggregate statistic", "file_format": "PDF", "license_or_usage_notes": "Official DES publication.",
        "download_date": "", "access_status": "DOWNLOADED", "variables_of_interest": "housing indicators",
        "quality_notes": "Raw PDF stored; no row-level housing imputation.",
    },
    {
        "source_id": "SRC_DATA_GOV_TN_GLANCE_2019", "source_name": "Tamil Nadu at a Glance 2019 catalog",
        "publisher": "Open Government Data Platform India / Tamil Nadu DES", "official_or_secondary": "Official",
        "source_url": "https://tn.data.gov.in/catalog/tamil-nadu-glance-2019-tnglance2019",
        "download_url": "https://tn.data.gov.in/catalog/tamil-nadu-glance-2019-tnglance2019",
        "dataset_name": "Tamil Nadu at a Glance 2019", "dataset_description": "OGD catalog provenance.",
        "reference_year": "2019", "publication_year": "2019", "geographic_level": "State",
        "unit_of_observation": "Aggregate statistic catalog", "file_format": "HTML/catalog",
        "license_or_usage_notes": "Government Open Data License metadata applies.", "download_date": "",
        "access_status": "DOWNLOADED", "variables_of_interest": "catalog provenance",
        "quality_notes": "Catalog saved; API detail extraction pending.",
    },
    {
        "source_id": "SRC_NFHS5_IIPS_2019_21", "source_name": "National Family Health Survey 5, Tamil Nadu",
        "publisher": "IIPS / Ministry of Health and Family Welfare, Government of India",
        "official_or_secondary": "Official", "source_url": "https://www.nfhsiips.in/nfhsuser/nfhs5.php",
        "download_url": "https://www.iipsdata.ac.in/datacatalog_detail/1",
        "dataset_name": "NFHS-5 household and household member data",
        "dataset_description": "Official NFHS survey data and reports; microdata may require approval.",
        "reference_year": "2019-2021", "publication_year": "2022", "geographic_level": "State/district estimates",
        "unit_of_observation": "Household/person survey records and aggregate estimates", "file_format": "PDF/registered microdata",
        "license_or_usage_notes": "Follow NFHS/IIPS/DHS data terms.", "download_date": "",
        "access_status": "MANUAL_DOWNLOAD_REQUIRED", "variables_of_interest": "amenities, wealth, health insurance",
        "quality_notes": "Not downloaded automatically because access terms may require registration.",
    },
    {
        "source_id": "SRC_NSS_MOSPI_CATALOG", "source_name": "NSS/NSO/MoSPI unit-level data catalog",
        "publisher": "MoSPI / National Statistics Office", "official_or_secondary": "Official",
        "source_url": "https://microdata.gov.in/NADA/index.php/catalog", "download_url": "https://microdata.gov.in/NADA/index.php/catalog",
        "dataset_name": "NSS public-use microdata catalog", "dataset_description": "Consumption, health, housing and other NSS rounds.",
        "reference_year": "Multiple", "publication_year": "Multiple", "geographic_level": "State/rural-urban",
        "unit_of_observation": "Household/person survey records", "file_format": "Registered/public-use microdata",
        "license_or_usage_notes": "MoSPI microdata portal rules apply.", "download_date": "",
        "access_status": "MANUAL_DOWNLOAD_REQUIRED", "variables_of_interest": "consumption, health expenditure, education, household characteristics",
        "quality_notes": "Needs round-specific source selection and access verification.",
    },
]
