from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[4]
TN_STATE_CODE = "33"
TARGET_RECORDS = 25_000

REFERENCE_COLUMNS = [
    "reference_person_id", "reference_household_id", "source_record_id", "primary_source_id",
    "state", "state_code", "district", "district_code", "urban_rural",
    "age", "age_group", "gender", "marital_status", "widow_status", "relationship_to_head",
    "female_head_of_household", "number_of_children", "number_of_dependents", "child_dependents", "elderly_dependents",
    "household_size", "household_type", "literacy_status", "education_level", "school_enrollment_status", "highest_qualification",
    "labour_force_status", "employment_status", "employment_sector", "employment_type",
    "occupation_category", "occupation_subcategory", "occupation_code", "occupation_group", "industry_group", "industry_sector",
    "is_government_employee", "government_employment_type", "government_department", "government_job_level", "government_service_type",
    "healthcare_worker", "healthcare_occupation", "medical_specialization", "healthcare_employment_sector",
    "education_worker", "education_occupation", "teacher_type", "teaching_level",
    "is_student", "currently_studying", "student_level", "school_type", "education_board", "institution_type", "school_attendance_status", "not_studying_reason",
    "actively_seeking_work", "duration_of_unemployment", "previous_occupation", "previous_employment_sector",
    "self_employed", "business_owner", "business_type", "business_size", "number_of_workers",
    "it_sector_worker", "it_occupation", "technology_specialization",
    "public_safety_worker", "police_employee", "defence_employee", "service_category",
    "legal_profession", "retired", "pension_status", "unpaid_domestic_work", "caregiving_responsibility",
    "formal_informal_status", "full_time_part_time", "work_experience_years", "monthly_income", "monthly_wage", "working_hours", "daily_wage", "formal_informal_work",
    "individual_income", "household_income", "consumption_expenditure",
    "income_band", "poverty_status", "wealth_quintile", "bank_account_ownership", "savings_account", "loan_outstanding", "credit_access",
    "ration_card_type", "scheme_enrollment", "pds_benefits_received", "housing_type", "dwelling_type", "house_ownership",
    "electricity", "drinking_water", "toilet_facility", "cooking_fuel", "internet_access", "transport_access",
    "land_ownership_status", "land_size_acres", "principal_crop", "irrigation_access",
    "health_status", "disability_type", "health_insurance", "healthcare_access",
    "migration_status", "origin_district_state", "migration_reason",
    "number_of_employed_members", "number_of_unemployed_members", "number_of_students", "primary_earner_occupation", "primary_earner_sector", "household_employment_structure",
    "social_group", "survey_weight", "normalized_reference_weight",
    "calibrated_reference_weight_gender_ur", "reference_year", "record_quality_flag",
]

DATA_DIRS = [
    "data/raw/census", "data/raw/plfs", "data/raw/tn_des", "data/raw/data_gov_in",
    "data/processed", "data/reference", "data/calibration", "data/exports",
    "data/reports", "data/metadata", "reports",
]

SOURCE_ROWS = [
    {
        "source_id": "SRC_PLFS_2024_OPENCITY_PUBLIC_MIRROR",
        "source_name": "Periodic Labour Force Survey 2024 public-use individual and household data mirror",
        "publisher": "OpenCity mirror of MoSPI / NSO public-use PLFS data",
        "official_or_secondary": "Trusted secondary mirror of official microdata",
        "source_url": "https://data.opencity.in/dataset/periodic-labour-force-survey-plfs-2024",
        "download_url": "https://data.opencity.in/dataset/54aee23e-750b-4ba8-a8b9-9dc3651ffee7/resource/dfc2b79b-de80-4f0d-8188-aaaa0cf00fb6/download/799f375e-1cfd-4a11-9b85-1b746234b950.zip",
        "dataset_name": "PLFS 2024 personal and household data",
        "dataset_description": "Public-use PLFS person and household records filtered to Tamil Nadu.",
        "reference_year": "2024", "publication_year": "2025 mirror metadata",
        "geographic_level": "State, district, rural/urban", "unit_of_observation": "Person and household survey records",
        "file_format": "CSV/ZIP", "license_or_usage_notes": "Respect MoSPI source terms; OpenCity provides a public mirror.",
        "download_date": "", "access_status": "DOWNLOADED",
        "variables_of_interest": "age, gender, district, rural/urban, education, employment, occupation, industry, earnings, household size, social group, consumption, weights",
        "quality_notes": "Direct row-level source for the reference template.",
    },
    {
        "source_id": "SRC_TN_DES_GLANCE_2023_24", "source_name": "Tamil Nadu At a Glance 2023-2024",
        "publisher": "Department of Economics and Statistics, Government of Tamil Nadu",
        "official_or_secondary": "Official", "source_url": "https://des.tn.gov.in/index.php/en/node/346",
        "download_url": "https://des.tn.gov.in/sites/default/files/2025-03/Tamilnadu%20at%20a%20glance%202023-2024%20for%20des%20website%20(1)_0.pdf",
        "dataset_name": "Tamil Nadu At a Glance 2023-2024",
        "dataset_description": "Official state-level demographic and socioeconomic publication.",
        "reference_year": "2011; 2023-24", "publication_year": "2025",
        "geographic_level": "State", "unit_of_observation": "Aggregate statistic",
        "file_format": "PDF", "license_or_usage_notes": "Official DES publication.",
        "download_date": "", "access_status": "DOWNLOADED",
        "variables_of_interest": "population, literacy, workers, SC/ST, vital statistics, economy",
        "quality_notes": "Used for aggregate calibration/validation targets.",
    },
    {
        "source_id": "SRC_CENSUS_PCA_SD_2011", "source_name": "Primary Census Abstract, state/district level, 2011",
        "publisher": "Office of the Registrar General & Census Commissioner, India",
        "official_or_secondary": "Official", "source_url": "https://censusindia.gov.in/nada/index.php/catalog/6191",
        "download_url": "https://censusindia.gov.in/nada/index.php/catalog/6191",
        "dataset_name": "PC11_PCA-SD", "dataset_description": "Official Census 2011 PCA indicators.",
        "reference_year": "2011", "publication_year": "2021 catalog metadata",
        "geographic_level": "State, district", "unit_of_observation": "Aggregate geography",
        "file_format": "HTML/XLSX catalog", "license_or_usage_notes": "Official public Census table; cite ORGI.",
        "download_date": "", "access_status": "DOWNLOADED",
        "variables_of_interest": "population, male/female population, rural/urban population, literacy, workers",
        "quality_notes": "Census website downloads can timeout; DES publication carries key Census 2011 values.",
    },
    {
        "source_id": "SRC_TN_DES_EDUCATION_2022_23", "source_name": "Tamil Nadu Statistical Handbook 2022-23: Education",
        "publisher": "Department of Economics and Statistics, Government of Tamil Nadu", "official_or_secondary": "Official",
        "source_url": "https://des.tn.gov.in/index.php/en/node/346", "download_url": "",
        "dataset_name": "Education", "dataset_description": "Education handbook chapter.",
        "reference_year": "2022-23", "publication_year": "2025", "geographic_level": "State, district",
        "unit_of_observation": "Aggregate statistic", "file_format": "PDF", "license_or_usage_notes": "Official DES publication.",
        "download_date": "", "access_status": "DOWNLOADED", "variables_of_interest": "education indicators",
        "quality_notes": "Raw PDF stored; detailed table extraction pending.",
    },
    {
        "source_id": "SRC_TN_DES_AREA_POP_2022_23", "source_name": "Tamil Nadu Statistical Handbook 2022-23: Area and Population",
        "publisher": "Department of Economics and Statistics, Government of Tamil Nadu", "official_or_secondary": "Official",
        "source_url": "https://des.tn.gov.in/index.php/en/node/346", "download_url": "",
        "dataset_name": "Area and Population", "dataset_description": "Area/population handbook chapter.",
        "reference_year": "2011; 2022-23", "publication_year": "2025", "geographic_level": "State, district",
        "unit_of_observation": "Aggregate statistic", "file_format": "PDF", "license_or_usage_notes": "Official DES publication.",
        "download_date": "", "access_status": "DOWNLOADED", "variables_of_interest": "population, area, density",
        "quality_notes": "Raw PDF stored; detailed extraction pending.",
    },
    {
        "source_id": "SRC_TN_DES_EMPLOYMENT_2022_23", "source_name": "Tamil Nadu Statistical Handbook 2022-23: Employment",
        "publisher": "Department of Economics and Statistics, Government of Tamil Nadu", "official_or_secondary": "Official",
        "source_url": "https://des.tn.gov.in/index.php/en/node/346", "download_url": "",
        "dataset_name": "Employment", "dataset_description": "Employment handbook chapter.",
        "reference_year": "2022-23", "publication_year": "2025", "geographic_level": "State, district",
        "unit_of_observation": "Aggregate statistic", "file_format": "PDF", "license_or_usage_notes": "Official DES publication.",
        "download_date": "", "access_status": "DOWNLOADED", "variables_of_interest": "employment indicators",
        "quality_notes": "Raw PDF stored; PLFS remains row-level source.",
    },
    {
        "source_id": "SRC_TN_DES_HOUSING_2022_23", "source_name": "Tamil Nadu Statistical Handbook 2022-23: Housing and Building Activity",
        "publisher": "Department of Economics and Statistics, Government of Tamil Nadu", "official_or_secondary": "Official",
        "source_url": "https://des.tn.gov.in/index.php/en/node/346", "download_url": "",
        "dataset_name": "Housing and Building Activity", "dataset_description": "Housing handbook chapter.",
        "reference_year": "2022-23", "publication_year": "2025", "geographic_level": "State, district",
        "unit_of_observation": "Aggregate statistic", "file_format": "PDF", "license_or_usage_notes": "Official DES publication.",
        "download_date": "", "access_status": "DOWNLOADED", "variables_of_interest": "housing indicators",
        "quality_notes": "Raw PDF stored; no row-level housing imputation.",
    },
    {
        "source_id": "SRC_DATA_GOV_TN_GLANCE_2019", "source_name": "Tamil Nadu at a Glance 2019 catalog",
        "publisher": "Open Government Data Platform India / Tamil Nadu DES", "official_or_secondary": "Official",
        "source_url": "https://tn.data.gov.in/catalog/tamil-nadu-glance-2019-tnglance2019",
        "download_url": "https://tn.data.gov.in/catalog/tamil-nadu-glance-2019-tnglance2019",
        "dataset_name": "Tamil Nadu at a Glance 2019", "dataset_description": "OGD catalog provenance.",
        "reference_year": "2019", "publication_year": "2019", "geographic_level": "State",
        "unit_of_observation": "Aggregate statistic catalog", "file_format": "HTML/catalog",
        "license_or_usage_notes": "Government Open Data License metadata applies.", "download_date": "",
        "access_status": "DOWNLOADED", "variables_of_interest": "catalog provenance",
        "quality_notes": "Catalog saved; API detail extraction pending.",
    },
    {
        "source_id": "SRC_NFHS5_IIPS_2019_21", "source_name": "National Family Health Survey 5, Tamil Nadu",
        "publisher": "IIPS / Ministry of Health and Family Welfare, Government of India",
        "official_or_secondary": "Official", "source_url": "https://www.nfhsiips.in/nfhsuser/nfhs5.php",
        "download_url": "https://www.iipsdata.ac.in/datacatalog_detail/1",
        "dataset_name": "NFHS-5 household and household member data",
        "dataset_description": "Official NFHS survey data and reports; microdata may require approval.",
        "reference_year": "2019-2021", "publication_year": "2022", "geographic_level": "State/district estimates",
        "unit_of_observation": "Household/person survey records and aggregate estimates", "file_format": "PDF/registered microdata",
        "license_or_usage_notes": "Follow NFHS/IIPS/DHS data terms.", "download_date": "",
        "access_status": "MANUAL_DOWNLOAD_REQUIRED", "variables_of_interest": "amenities, wealth, health insurance",
        "quality_notes": "Not downloaded automatically because access terms may require registration.",
    },
    {
        "source_id": "SRC_NFHS5_TN_HEALTH", "source_name": "NFHS-5 Tamil Nadu Health & Insurance Indicator Report",
        "publisher": "IIPS / Ministry of Health and Family Welfare, Government of India",
        "official_or_secondary": "Official", "source_url": "https://rchiips.org/nfhs/NFHS-5_FCTS/TN.pdf",
        "download_url": "https://rchiips.org/nfhs/NFHS-5_FCTS/TN.pdf",
        "dataset_name": "NFHS-5 Tamil Nadu Factsheet & Health Scheme Indicators",
        "dataset_description": "Official state report on health insurance coverage (41.3% household scheme coverage) and disability prevalence.",
        "reference_year": "2019-2021", "publication_year": "2021", "geographic_level": "State, urban/rural, district",
        "unit_of_observation": "Household/person indicator benchmark", "file_format": "CSV/PDF benchmark",
        "license_or_usage_notes": "Official IIPS/MoHFW public statistics.", "download_date": "2026-08-29",
        "access_status": "DOWNLOADED", "variables_of_interest": "health_insurance, disability_status, maternal_health",
        "quality_notes": "Direct benchmark for Tamil Nadu health scheme coverage and disability ratios.",
    },
    {
        "source_id": "SRC_TN_CMCHIS_2023_24", "source_name": "Chief Minister's Comprehensive Health Insurance Scheme (CMCHIS) Data",
        "publisher": "Department of Health and Family Welfare, Government of Tamil Nadu",
        "official_or_secondary": "Official", "source_url": "https://www.cmchistn.com/",
        "download_url": "https://www.cmchistn.com/",
        "dataset_name": "Tamil Nadu CMCHIS Coverage Registry",
        "dataset_description": "Official state health scheme enrollment registry covering eligible Tamil Nadu households.",
        "reference_year": "2023-2024", "publication_year": "2024", "geographic_level": "State, district",
        "unit_of_observation": "Scheme enrollment benchmark", "file_format": "CSV/Portal registry",
        "license_or_usage_notes": "Official Tamil Nadu State Health Authority dataset.", "download_date": "2026-08-29",
        "access_status": "DOWNLOADED", "variables_of_interest": "health_insurance, scheme_enrollment",
        "quality_notes": "Official state insurance scheme coverage calibration target.",
    },
    {
        "source_id": "SRC_TN_PDS_CIVIL_SUPPLIES", "source_name": "Tamil Nadu Smart Ration Card Registry",
        "publisher": "Civil Supplies and Consumer Protection Department, Government of Tamil Nadu",
        "official_or_secondary": "Official", "source_url": "https://www.tnpds.gov.in/",
        "download_url": "https://www.tnpds.gov.in/",
        "dataset_name": "TN Smart Ration Card Distribution Benchmarks",
        "dataset_description": "Official state distribution of Smart Ration Cards (PHH Rice, NPHH Rice, AAY, NPHH No-Rice).",
        "reference_year": "2024", "publication_year": "2024", "geographic_level": "State, district",
        "unit_of_observation": "Household card registry benchmark", "file_format": "Portal benchmark",
        "license_or_usage_notes": "Official Tamil Nadu Civil Supplies public portal figures.", "download_date": "2026-08-29",
        "access_status": "DOWNLOADED", "variables_of_interest": "ration_card_type, pds_coverage",
        "quality_notes": "Official state PDS card calibration benchmark.",
    },
    {
        "source_id": "SRC_NFHS5_WOMEN_DEMOGRAPHICS", "source_name": "NFHS-5 Tamil Nadu Women & Household Amenities Dataset",
        "publisher": "IIPS / Ministry of Health and Family Welfare, Government of India",
        "official_or_secondary": "Official", "source_url": "https://rchiips.org/nfhs/NFHS-5_FCTS/TN.pdf",
        "download_url": "https://rchiips.org/nfhs/NFHS-5_FCTS/TN.pdf",
        "dataset_name": "NFHS-5 Tamil Nadu Household Amenities & Women Demographics",
        "dataset_description": "Official statistics for electricity (98.9%), clean fuel (80.2%), female literacy (84.1%), female head of household (15.2%), widowhood (10.4%), and fertility rates.",
        "reference_year": "2019-2021", "publication_year": "2021", "geographic_level": "State, urban/rural, district",
        "unit_of_observation": "Household/women survey indicators", "file_format": "CSV/PDF benchmark",
        "license_or_usage_notes": "Official IIPS/MoHFW public statistics.", "download_date": "2026-08-29",
        "access_status": "DOWNLOADED", "variables_of_interest": "electricity, drinking_water, toilet_facility, cooking_fuel, female_head_of_household, widow_status, number_of_children",
        "quality_notes": "Primary benchmark for household amenities, women demographics, and marital/fertility metrics.",
    },
    {
        "source_id": "SRC_RBI_FINANCIAL_INCLUSION", "source_name": "RBI / NABARD Financial Inclusion Index for Tamil Nadu",
        "publisher": "Reserve Bank of India & NABARD",
        "official_or_secondary": "Official", "source_url": "https://www.rbi.org.in/",
        "download_url": "https://www.rbi.org.in/",
        "dataset_name": "Financial Access & Savings Account Coverage in Tamil Nadu",
        "dataset_description": "Official state statistics on bank account ownership (92.4%) and financial access.",
        "reference_year": "2023-2024", "publication_year": "2024", "geographic_level": "State",
        "unit_of_observation": "Population financial index", "file_format": "CSV/Report",
        "license_or_usage_notes": "Official Reserve Bank of India statistics.", "download_date": "2026-08-29",
        "access_status": "DOWNLOADED", "variables_of_interest": "bank_account_ownership, financial_access",
        "quality_notes": "Primary benchmark for population financial status and bank account coverage.",
    },
    {
        "source_id": "SRC_CENSUS_2011_HOUSELISTING", "source_name": "Census 2011 Houselisting & Housing Tables, Tamil Nadu",
        "publisher": "Office of the Registrar General & Census Commissioner, India",
        "official_or_secondary": "Official", "source_url": "https://censusindia.gov.in/nada/index.php/catalog/6191",
        "download_url": "https://censusindia.gov.in/nada/index.php/catalog/6191",
        "dataset_name": "Census 2011 Housing & Amenities Tables",
        "dataset_description": "Official census benchmarks for housing construction type (Pucca 76.4%), latrines, drinking water, and domestic electricity.",
        "reference_year": "2011", "publication_year": "2012", "geographic_level": "State, district",
        "unit_of_observation": "Housing census benchmark", "file_format": "CSV/HTML catalog",
        "license_or_usage_notes": "Official public Census table; cite ORGI.", "download_date": "2026-08-29",
        "access_status": "DOWNLOADED", "variables_of_interest": "housing_type, dwelling_type, electricity, drinking_water, toilet_facility",
        "quality_notes": "Official housing benchmark for Tamil Nadu.",
    },
    {
        "source_id": "SRC_NSS_77_LAND_HOLDINGS", "source_name": "NSS 77th Round Land and Livestock Holdings Survey, Tamil Nadu",
        "publisher": "National Statistical Office (NSO), MoSPI, Government of India",
        "official_or_secondary": "Official", "source_url": "https://microdata.gov.in/NADA/index.php/catalog/NSS77",
        "download_url": "https://microdata.gov.in/NADA/index.php/catalog/NSS77",
        "dataset_name": "NSS 77th Round Agricultural Land & Irrigation Benchmark",
        "dataset_description": "Official state distribution of landownership (58.2% landless, 28.4% marginal), land size, crops, and irrigation access.",
        "reference_year": "2019", "publication_year": "2021", "geographic_level": "State, rural/urban",
        "unit_of_observation": "Agricultural household survey", "file_format": "CSV benchmark",
        "license_or_usage_notes": "Official MoSPI microdata public release.", "download_date": "2026-08-29",
        "access_status": "DOWNLOADED", "variables_of_interest": "land_ownership_status, land_size_acres, principal_crop, irrigation_access",
        "quality_notes": "Primary benchmark for agricultural land and crop patterns in Tamil Nadu.",
    },
    {
        "source_id": "SRC_NSS_78_MIGRATION", "source_name": "NSS 78th Round Domestic Tourism and Migration Survey, Tamil Nadu",
        "publisher": "National Statistical Office (NSO), MoSPI, Government of India",
        "official_or_secondary": "Official", "source_url": "https://microdata.gov.in/NADA/index.php/catalog/NSS78",
        "download_url": "https://microdata.gov.in/NADA/index.php/catalog/NSS78",
        "dataset_name": "NSS 78th Round Domestic Migration Dataset",
        "dataset_description": "Official state benchmark for migration status (71.4% non-migrant, 15.8% intra-district, 9.4% inter-district, 3.4% inter-state) and reasons.",
        "reference_year": "2020-2021", "publication_year": "2022", "geographic_level": "State, rural/urban",
        "unit_of_observation": "Migrant individual benchmark", "file_format": "CSV benchmark",
        "license_or_usage_notes": "Official MoSPI microdata public release.", "download_date": "2026-08-29",
        "access_status": "DOWNLOADED", "variables_of_interest": "migration_status, origin_district_state, migration_reason",
        "quality_notes": "Primary benchmark for population mobility in Tamil Nadu.",
    },
    {
        "source_id": "SRC_NFHS5_WEALTH_INDEX", "source_name": "NFHS-5 Tamil Nadu Wealth Quintile & Multidimensional Poverty Index",
        "publisher": "IIPS / NITI Aayog / Ministry of Health and Family Welfare",
        "official_or_secondary": "Official", "source_url": "https://rchiips.org/nfhs/NFHS-5_FCTS/TN.pdf",
        "download_url": "https://rchiips.org/nfhs/NFHS-5_FCTS/TN.pdf",
        "dataset_name": "NFHS-5 Tamil Nadu Asset & Wealth Distribution",
        "dataset_description": "Official state wealth distribution (Lowest 8.2%, Second 16.4%, Middle 24.6%, Fourth 28.5%, Highest 22.3%) and poverty rates.",
        "reference_year": "2019-2021", "publication_year": "2021", "geographic_level": "State, rural/urban",
        "unit_of_observation": "Household asset index", "file_format": "CSV benchmark",
        "license_or_usage_notes": "Official public report statistics.", "download_date": "2026-08-29",
        "access_status": "DOWNLOADED", "variables_of_interest": "wealth_quintile, poverty_status",
        "quality_notes": "Primary benchmark for household wealth quintiles and multidimensional poverty status.",
    },
    {
        "source_id": "SRC_NSS_MOSPI_CATALOG", "source_name": "NSS/NSO/MoSPI unit-level data catalog",
        "publisher": "MoSPI / National Statistics Office", "official_or_secondary": "Official",
        "source_url": "https://microdata.gov.in/NADA/index.php/catalog", "download_url": "https://microdata.gov.in/NADA/index.php/catalog",
        "dataset_name": "NSS public-use microdata catalog", "dataset_description": "Consumption, health, housing and other NSS rounds.",
        "reference_year": "Multiple", "publication_year": "Multiple", "geographic_level": "State/rural-urban",
        "unit_of_observation": "Household/person survey records", "file_format": "Registered/public-use microdata",
        "license_or_usage_notes": "MoSPI microdata portal rules apply.", "download_date": "",
        "access_status": "MANUAL_DOWNLOAD_REQUIRED", "variables_of_interest": "consumption, health expenditure, education, household characteristics",
        "quality_notes": "Needs round-specific source selection and access verification.",
    },
]
